#!/usr/bin/env bash
# codebox @VERSION@ — self-extracting bundle.
#
# Generated by packaging/build.sh: this header is followed by a gzipped tar of the
# codebox tree (bin/, scripts/, vm/, ...). Running it unpacks that tree into a cache
# directory once, then hands over to the real bin/codebox. Do not edit by hand.
set -euo pipefail

CODEBOX_BUNDLE_VERSION="@VERSION@"
# Version plus a hash of the payload, so a rebuilt bundle never reuses a stale unpack.
CODEBOX_BUNDLE_ID="@BUNDLE_ID@"

# Find this file even when it is reached through a symlink (readlink -f is not
# portable to macOS, so walk the links ourselves).
self="${BASH_SOURCE[0]}"
while [ -L "$self" ]; do
  link="$(readlink "$self")"
  case "$link" in
    /*) self="$link" ;;
    *)  self="$(dirname "$self")/$link" ;;
  esac
done
self="$(cd "$(dirname "$self")" && pwd)/$(basename "$self")"

# Own a subdirectory rather than ~/.cache/codebox itself: on a VM that directory
# also holds the GitHub token cache (vm/gh-app-token.sh).
cache_root="${CODEBOX_CACHE_DIR:-${XDG_CACHE_HOME:-$HOME/.cache}/codebox}/bundle"
target="$cache_root/$CODEBOX_BUNDLE_ID"

if [ ! -x "$target/bin/codebox" ]; then
  mkdir -p "$cache_root"
  # The payload starts on the line after the marker. Search only the header so we
  # never hand the binary tail to grep.
  offset="$(head -n 120 "$self" | grep -a -n '^__CODEBOX_PAYLOAD__$' | head -1 | cut -d: -f1)"
  [ -n "$offset" ] || { echo "codebox: corrupt bundle (no payload marker)" >&2; exit 1; }

  tmp="$(mktemp -d "$cache_root/.extract.XXXXXX")"
  if ! tail -n +"$((offset + 1))" "$self" | tar -xzf - -C "$tmp"; then
    rm -rf "$tmp"
    echo "codebox: could not unpack the bundle (truncated download?)" >&2
    exit 1
  fi
  # Another codebox may have unpacked the same bundle while we were working; the
  # first one to land wins and we drop ours. If we lost the race between the test
  # and the move, our directory ends up nested inside the winner's — clean that up.
  if [ -d "$target" ] || ! mv "$tmp" "$target" 2>/dev/null; then
    rm -rf "$tmp"
  fi
  rm -rf "$target/.extract."* 2>/dev/null || true
  [ -x "$target/bin/codebox" ] || {
    echo "codebox: failed to unpack the bundle into $target" >&2; exit 1; }
fi

exec bash "$target/bin/codebox" "$@"
__CODEBOX_PAYLOAD__
